code --install-extension aaron-bond.better-comments
code --install-extension chmln.better-whitespace
code --install-extension christian-kohler.path-intellisense
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension CoenraadS.bracket-pair-colorizer-2
code --install-extension eamodio.gitlens
# code --install-extension emmanuelbeziat.vscode-great-icons
code --install-extension Equinusocio.vsc-material-theme
code --install-extension foxundermoon.shell-format
code --install-extension hbenl.vscode-test-explorer
code --install-extension igress.python-coding-conventions
code --install-extension jprestidge.theme-material-theme
code --install-extension lamartire.git-indicators
code --install-extension littlefoxteam.vscode-python-test-adapter
code --install-extension magicstack.MagicPython
code --install-extension mde.select-highlight-minimap
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.python
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode.sublime-keybindings
code --install-extension Mukundan.python-docs
code --install-extension pprice.better-merge
code --install-extension SBSnippets.pytorch-snippets
code --install-extension Shan.code-settings-sync
code --install-extension shardulm94.trailing-spaces
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension tht13.python
code --install-extension tickleforce.scrolloff
code --install-extension tobiasalthoff.atom-material-theme
code --install-extension uyiosa-enabulele.reopenclosedtab
code --install-extension VisualStudioExptTeam.vscodeintellicode
# code --install-extension vscode-icons-team.vscode-icons
code --install-extension wayou.vscode-todo-highlight
code --install-extension yzhang.markdown-all-in-one
code --install-extension zhuangtongfa.Material-theme